version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/tmp

    steps:
      - checkout

      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq install awscli

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cp _config.prod.yaml _config.yaml
            else 
              cp _config.staging.yaml _config.yaml
            fi
      - run: yarn run hexo generate
      - store_artifacts:
          path: ~/tmp/public
      - deploy:
          name: Deploy to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              .circleci/deploy.sh "./public" "in.bucket.blog.ircmaxell.com"
            elif [ "${CIRCLE_BRANCH}" == "blog_v2" ]; then
              .circleci/deploy.sh "./public" "in.bucket.beta.blog.ircmaxell.com"
            fi
