# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: ClassicOldSong
    url: https://ccoooss.com

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: GitHub
    slug: github
    url: https://github.com/ircmaxell
    new_window: true


# widgets
widgets:
  - about
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/ircmaxell
- slug: twitter
  url: https://twitter.com/ircmaxell
- slug: rss
	url: /atom.xml
